version: '2'
services:
    adap_report-app:
        image: adap_report
        external_links:
            - adap_report-postgresql:postgresql
            - adap_report-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/adap_report
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    adap_report-postgresql:
        extends:
            file: postgresql.yml
            service: adap_report-postgresql
    adap_report-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: adap_report-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
